[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://reaknotron.freemyip.com:4000/*"
  to = "https://reaknotron.freemyip.com:4000/:splat"
  status = 301
  force = true